name: marabou-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=2.1.0=py38h06a4308_0
  - aiohappyeyeballs=2.4.0=py38h06a4308_0
  - aiohttp=3.10.5=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anaconda-anon-usage=0.7.5=pyhb46e38b_100
  - anaconda-client=1.12.3=py38h06a4308_0
  - anaconda-cloud-auth=0.5.1=py38h06a4308_0
  - anaconda-navigator=2.6.3=py38h06a4308_0
  - annotated-types=0.6.0=py38h06a4308_0
  - anyio=4.2.0=py38h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - archspec=0.2.5=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - astor=0.8.1=py38h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.4=py38h06a4308_0
  - async-timeout=4.0.3=py38h06a4308_0
  - attrs=24.2.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py38h06a4308_0
  - boltons=23.0.0=py38h06a4308_0
  - bottleneck=1.3.7=py38ha9d4c09_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cachetools=5.3.3=py38h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - cloudpickle=3.0.0=py38h06a4308_0
  - coloredlogs=15.0.1=py38h06a4308_2
  - comm=0.2.1=py38h06a4308_0
  - conda=24.9.2=py38h06a4308_0
  - conda-content-trust=0.2.0=py38h06a4308_1
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py38h06a4308_0
  - conda-package-streaming=0.10.0=py38h06a4308_0
  - conda-repo-cli=1.0.114=py38h06a4308_0
  - conda-token=0.5.0=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=43.0.0=py38hdda0065_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=0.12.2=py38h5eee18b_0
  - dask-core=2023.4.1=py38h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py38h06a4308_0
  - exceptiongroup=1.2.0=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=6.1.1=h4c62175_0
  - fftw=3.3.9=h5eee18b_2
  - filelock=3.13.1=py38h06a4308_0
  - flatbuffers=24.3.25=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozendict=2.4.2=py38h5eee18b_0
  - frozenlist=1.4.0=py38h5eee18b_0
  - fsspec=2024.6.1=py38h06a4308_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gettext=0.21.0=h39681ba_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.1.2=py38heeb90bb_0
  - google-auth=2.29.0=py38h06a4308_0
  - google-auth-oauthlib=0.5.2=py38h06a4308_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - grpc-cpp=1.48.2=he1ff14a_1
  - grpcio=1.48.2=py38he1ff14a_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py38h06a4308_0
  - h5py=2.10.0=py38hd6299e0_1
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.10.6=h3ffc7dd_1
  - httpcore=1.0.2=py38h06a4308_0
  - httpx=0.27.0=py38h06a4308_0
  - humanfriendly=10.0=py38h06a4308_1
  - icu=58.2=he6710b0_3
  - idna=3.7=py38h06a4308_0
  - imageio=2.33.1=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py38h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=3.1.4=py38h06a4308_0
  - joblib=1.4.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.33=py38h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38h06a4308_0
  - jsonschema-specifications=2023.7.1=py38h06a4308_0
  - jupyter-lsp=2.2.0=py38h06a4308_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - jupyter_events=0.10.0=py38h06a4308_0
  - jupyter_server=2.14.1=py38h06a4308_0
  - jupyter_server_terminals=0.4.4=py38h06a4308_1
  - jupyterlab=4.2.5=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38h06a4308_0
  - keras=2.4.3=hd3eb1b0_0
  - keras-base=2.4.3=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyring=24.3.1=py38h06a4308_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py38h06a4308_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=h42c8aad_2
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.6.2=h6ac8c49_3
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libllvm14=14.0.6=hecde1de_4
  - libmamba=1.5.8=hfe524e5_2
  - libmambapy=1.5.8=py38h2dafd23_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.20=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.5.1=hffd6297_1
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py38h06a4308_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - menuinst=2.2.0=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - more-itertools=10.3.0=py38h06a4308_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py38h06a4308_0
  - multidict=6.0.4=py38h5eee18b_0
  - mypy=1.11.2=py38h5eee18b_0
  - mypy_extensions=1.0.0=py38h06a4308_0
  - mysql=5.7.24=h721c034_2
  - navigator-updater=0.5.1=py38h06a4308_0
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.16.4=py38h06a4308_0
  - nbformat=5.10.4=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - networkx=3.1=py38h06a4308_0
  - notebook=7.2.2=py38h06a4308_1
  - notebook-shim=0.2.3=py38h06a4308_0
  - nspr=4.37=h8459abe_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py38hc78ab66_1
  - numpy=1.23.5=py38hf6e8229_1
  - numpy-base=1.23.5=py38h060ed82_1
  - oauthlib=3.2.2=py38h06a4308_0
  - onnxruntime=1.17.1=py38hf70ce4d_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.19=h1b28b03_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - overrides=7.4.0=py38h06a4308_0
  - packaging=24.1=py38h06a4308_0
  - pandas=2.0.3=py38h1128e8f_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py38h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkce=1.0.3=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - platformdirs=3.10.0=py38h06a4308_0
  - pluggy=1.0.0=py38h06a4308_1
  - ply=3.11=py38_0
  - pooch=1.7.0=py38h06a4308_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - protobuf=3.20.3=py38h6a678d5_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py38h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.8.2=py38h06a4308_0
  - pydantic-core=2.20.1=py38hb02cf49_0
  - pygments=2.15.1=py38h06a4308_1
  - pyjwt=2.8.0=py38h06a4308_0
  - pyopenssl=24.2.1=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pyqtwebengine=5.15.10=py38h6a678d5_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-dotenv=0.21.0=py38h06a4308_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-flatbuffers=24.3.25=py38h06a4308_0
  - python-json-logger=2.0.7=py38h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.3.0=cpu_py38h2a1f63a_0
  - pytz=2024.1=py38h06a4308_0
  - pywavelets=1.4.1=py38h5eee18b_0
  - pyyaml=6.0.2=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtpy=2.4.1=py38h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py38h06a4308_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py38h06a4308_0
  - requests-oauthlib=2.0.0=py38h06a4308_0
  - requests-toolbelt=1.0.0=py38h06a4308_0
  - rfc3339-validator=0.1.4=py38h06a4308_0
  - rfc3986-validator=0.1.1=py38h06a4308_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.18.6=py38h5eee18b_0
  - ruamel.yaml.clib=0.2.8=py38h5eee18b_0
  - scikit-image=0.19.3=py38h6a678d5_1
  - scikit-learn=1.3.0=py38h1128e8f_1
  - scipy=1.10.1=py38hf6e8229_1
  - seaborn=0.13.2=py38h06a4308_0
  - secretstorage=3.3.1=py38h06a4308_1
  - semver=3.0.2=py38h06a4308_0
  - send2trash=1.8.2=py38h06a4308_0
  - setuptools=75.1.0=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py38h06a4308_0
  - soupsieve=2.5=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.3=py38h06a4308_0
  - tabulate=0.9.0=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.12.1=py38h06a4308_0
  - tensorboard-data-server=0.7.0=py38h52d8a92_1
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tensorflow=2.4.1=mkl_py38hb2083e0_0
  - tensorflow-base=2.4.1=mkl_py38h43e0292_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=2.1.0=py38h06a4308_0
  - terminado=0.17.1=py38h06a4308_0
  - tesseract=5.2.0=h6a678d5_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py38h06a4308_0
  - toolz=0.12.0=py38h06a4308_0
  - torchvision=0.18.1=cpu_py38h54128f0_0
  - tornado=6.4.1=py38h5eee18b_0
  - tqdm=4.66.5=py38h2f386ee_0
  - traitlets=5.14.3=py38h06a4308_0
  - typing-extensions=4.11.0=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - ujson=5.10.0=py38h6a678d5_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=2.2.3=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38h06a4308_0
  - werkzeug=3.0.3=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - yarl=1.11.0=py38h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py38h2c38b39_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - altgraph==0.17.4
      - arrow==1.3.0
      - bcrypt==4.3.0
      - binaryornot==0.4.4
      - chardet==5.2.0
      - cookiecutter==2.6.0
      - evdev==1.9.2
      - graphviz==0.20.3
      - jupyterlab-prolog-codemirror-extension==0.0.2
      - libevdev==0.12
      - maraboupy==2.0.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - metakernel==0.30.3
      - octave-kernel==0.36.0
      - onnx==1.17.0
      - paramiko==3.5.1
      - prolog-kernel==0.0.9
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.9
      - pynacl==1.6.0
      - pynput==1.8.1
      - pyswip==0.3.1
      - python-slugify==8.0.4
      - python-xlib==0.33
      - remarkable-mouse==7.1.1
      - rich==14.1.0
      - screeninfo==0.8.1
      - text-unidecode==1.3
      - tf2onnx==1.16.1
      - types-python-dateutil==2.9.0.20241206
prefix: /home/merkouris/anaconda3/envs/marabou-env
